import setuptools

setuptools.setup(
    name="glabel",
    version="0.3.1",
    author="Tobias Zillig",
    author_email="tobias.zillig@fau.de",
    description="Deep-learning enhanced annotation tool for vocal fold surfaces.",
    license="GPLv3+",
    packages=setuptools.find_packages(),
    install_requires=[
        "PyQt5==5.9.2",
        "imageio==2.6.1",
        "imageio-ffmpeg",
        "opencv-python",
        "scikit-image==0.16.2",
        "scikit-learn==0.22.1",
        "scikit-video",
        "scipy==1.1.0",
        "albumentations==0.4.5",
        "efficientnet==1.1.0",
        "flammkuchen==0.9.2",
        "qdarkstyle==2.8",
        "segmentation_models==1.0.1",
        "tensorflow==2.1.0",
        "pyqtgraph==0.11.0",
        "pyopengl==3.1.1a1",
        "pandas==0.25.3",
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Operating System :: OS Independent",
    ],
    keywords="annotation medical landmarks",
    url="https://github.com/TBSZLG/glabel",
    python_requires='>=3.6',
)