import setuptools

setuptools.setup(
    name="glabel",
    version="0.3.2",
    author="Tobias Zillig",
    author_email="tobias.zillig@fau.de",
    description="Deep-learning enhanced annotation tool for vocal fold surfaces.",
    license="GPLv3+",
    packages=setuptools.find_packages(),
    install_requires=[
        "PyQt5",
        "imageio",
        "imageio-ffmpeg",
        "opencv-python",
        "scikit-image",
        "scikit-learn",
        "scikit-video",
        "scipy",
        "numpy",
        "albumentations",
        "efficientnet",
        "flammkuchen",
        "qdarkstyle",
        "segmentation_models",
        "tensorflow",
        "pyqtgraph",
        "pyopengl",
        "pandas",
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Operating System :: OS Independent",
    ],
    keywords="annotation medical landmarks",
    url="https://github.com/ankilab/glabel",
    python_requires='>=3.6',
)